Digital in
adafruit/Adafruit_CircuitPython_SI4713 pull request #23
Opened 2021-12-01 11:57 UTC by sheimers

I have tried to extend the adafruit_si4713.py module to enable the digital audio input (I2S) of the Si4721 chip. It's still compatible with analog in / Si4713.
I had limited success, I eventually got digital audio in working, but not reproducible.

In addition to the modified adafruit_si4713.py, this pull request also includes a simple example script for a transmitter with digital audio input, examples/simpleDigitalTx.py
The example includes comments that describe how the Si4721 can be connected to a Raspberry Pi with I2S (hifiBerry) audio.
I'd be glad if someone could check my modifications and tell if there is a mistake or if it could be improved.

2021-12-14 10:40 UTC, sheimers commented
I did some more tests, it's not stable with the PCM output from the Raspi GPIO, but it works perfectly and reproducible with a CP2615 USB-to-I2S bridge evaluation board.

2022-01-18 19:19 UTC, askpatrickw commented
@sheimers  did you have a change to look at the CI failures?

2022-03-14 14:57 UTC, FoamyGuy requested changes
I added a few commits to get this passing the CI checks. 

I'm not super familiar with this hardware, and I don't have one for testing, I did review the code though and have one suggestion to either remove the various print statements or add a `verbose` argument to the constructor that enables them.

2022-03-14 14:57 UTC, FoamyGuy commented on adafruit_si4713.py
> +            print("have set, return false")
same as other prints, suggest removing or adding a `verbose` argument to `__init__()` that enables the printing

2022-03-14 14:57 UTC, FoamyGuy commented on adafruit_si4713.py
> +            print("have set, return false")
A few more here, suggest removing prints or adding a `verbose` argument to init to enable them.

2022-03-20 15:30 UTC, FoamyGuy commented
Going to close this for now. @sheimers if you get back to this to make the requested changes please free to re-open this, same for anyone else if someone else finds this and is interested in working on this functionality. You can also ping me if you have any trouble or need help.

2022-03-20 15:30 UTC, closed without merging