Add Missing Type Annotations
adafruit/Adafruit_CircuitPython_SI4713 pull request #24
Opened 2022-10-10 02:57 UTC by tcfranks

resolves #21 
submitted for review / comment

2022-10-13 23:47 UTC, tekktrik requested changes
Feedback below!

2022-10-13 23:47 UTC, tekktrik commented on adafruit_si4713.py
> +    def _set_rds_station(self, station: Optional[ReadableBuffer]) -> None:
It doesn't look like `station` can be `None` since the use of `len()` on it will cause a `TypeError`.  The `ReadableBuffer` type is sufficient.

2022-10-13 23:47 UTC, tekktrik commented on adafruit_si4713.py
> +    def _set_rds_buffer(self, rds_buffer: Optional[ReadableBuffer]) -> None:
Same thing here, `rds_buffer` can't be `None`.

2022-10-14 13:25 UTC, tcfranks commented
submitted for review with suggested changes

2022-10-17 02:08 UTC, tekktrik approved these changes
Looks good, thanks!

2022-10-17 02:08 UTC, merged